source 'https://rubygems.org'

gem 'jekyll', '~> 4.4.1'
gem 'jekyll-theme-so-simple', '~> 3.2'

# Jekyll plugins
group :jekyll_plugins do
  gem 'jekyll-seo-tag', '~> 2.8'
  gem 'jekyll-sitemap', '~> 1.4'
  gem 'jemoji', '~> 0.13.0'
end

# Windows and JRuby
platforms :windows, :jruby do
  gem 'tzinfo', '>= 1', '< 3'
  gem 'tzinfo-data'
end
# Performance-booster for Windows
gem 'wdm', '~> 0.1', :platforms => [:windows]
# Newer versions of the gem do not have a Java counterpart
gem 'http_parser.rb', '~> 0.6.0', :platforms => [:jruby]
